### ISSUE TITLE
Trash Icon is not displayed ( File Manager )

### ISSUE THREAD

**Issue by Ok9xNirab** [USBA/Cupertino-Mojave-iCons#2]
![Screenshot from 2019-06-10 02-29-14](https://user-images.githubusercontent.com/40653908/59163836-c2d16900-8b27-11e9-865d-2619435ab711.png)

These Trash icon is not displaying !! Please Fixed It as quick !!
Thanks. !!

**Comment by sunbearc22** [comment]
I just [noticed the same issue too](https://askubuntu.com/questions/1266605/trash-bin-icons-missing-how-to-get-them-back?noredirect=1#comment2143852_1266605). 

I have installed the latest version of your Cupertino-Catalina theme (and also your Big Sur theme). That resolved this issue. But I still see this warning.  

```
$ sudo update-icon-caches ~/.local/share/icons/*
[sudo] password for master: 
gtk-update-icon-cache: The generated cache was invalid.
WARNING: icon cache generation failed for ~/.local/share/icons/Cupertino-BigSur
gtk-update-icon-cache: The generated cache was invalid.
WARNING: icon cache generation failed for ~/.local/share/icons/Cupertino-Catalina
gtk-update-icon-cache: The generated cache was invalid.
WARNING: icon cache generation failed for ~/.local/share/icons/Cupertino-Catalina-iCons-master
gtk-update-icon-cache: The generated cache was invalid.
WARNING: icon cache generation failed for ~/.local/share/icons/Cupertino-iCons-master 

```

I found two occurrences of whitespace in filename: `apps/128/gnome-control-center datetime.png` and `apps/128/gnome-control-center sound.png`. replaced whitespace with `@` symbol. Warning no longer appears but missing empty trashcan icon is still missing.

Not sure why the older version, which was working fine, suddenly gave this missing empty trashcan issue.
